#!/usr/bin/python3


def raise_exception_msg(message=""):
    """NameError exception with a new message."""
    raise NameError(message)
